version: '3'

services:
  postgres:
    image: "postgres:14-alpine"
    environment:
      - POSTGRES_PASSWORD=123456

  redis:
    image: 'redis:latest'

  api:
    build:
      context: ./fib-app-backend
      dockerfile: Dockerfile.dev

    depends_on:
      - postgres
      - redis

    links:
      - postgres
      - redis

    volumes:
      - /app/node_modules
      - ./fib-app-backend:/app 

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=123456
      - PGPORT=5432

  fib-app:
    stdin_open: true

    environment:
      - WDS_SOCKET_PORT=0

    build:  
      context: ./fib-app-frontend
      dockerfile: Dockerfile.dev
 
    volumes:
      - /app/node_modules
      - ./fib-app-frontend:/app

  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile.dev

    volumes:
      - /app/node_modules
      - ./worker:/app

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    
  nginx:
    image: "nginx:stable"
    depends_on:
      - api
      - fib-app-frontend
    restart: always 

    ports:
      - '4050:80'

    volumes:
       - "./deployment/default.conf:/etc/nginx/conf.d/default.conf"

