version: "3"

services:
  api:
    build: ./fib-app-backend

    depends_on:
      - redis
      - postgres
      - worker

    links:
      - redis
      - postgres
      - worker

    volumes:
      - /app/node_modules
      - ./fib-app-backend:/app

    command: sh -c "npm run build && npm run start"

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=fib-db
      - PGPASSWORD=postgres
      - PGPORT=5432
      - PORT=3000
      - NODE_ENV=production

    ports:
      - 3000:3000

  worker:
    build: ./worker

    command: sh -c "npm run build && npm run start"

    volumes:
      - /app/node_modules
      - ./worker:/app

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production

    ports:
      - 3002:3002

  client:
    stdin_open: true

    depends_on:
      - api

    links:
      - api

    build: ./fib-app-frontend

    volumes:
      - /app/node_modules
      - ./fib-app-frontend:/app

    command: sh -c "rm -rf .next && npm run build && npm start"

    environment:
      - API_PORT=3000
      - NODE_ENV=production

    ports:
      - 3001:3001

  nginx:
    image: "nginx:stable"

    depends_on:
      - api
      - client
      - worker

    links:
      - api
      - client
      - worker

    restart: always

    ports:
      - "80:80"

    volumes:
      - "./fib-app-backend/deployment/nginx.conf:/etc/nginx/nginx.conf"

  redis:
    image: "redis:alpine"

  postgres:
    restart: always

    image: "postgres:14-alpine"

    volumes:
      - "./fib-app-backend/deployment/fib.sql:/docker-entrypoint-initdb.d/fib.sql"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fib-db
      - POSTGRES_PASSWORD=postgres
