name: Release

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "fib-app-backend"

    steps:
      - uses: actions/checkout@v2
      - run: docker build . -t retr0327/fib-app-backend
      - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker push retr0327/fib-app-backend
